version: '3'

services:

  postfix:
    image: ghcr.io/moerchel/docker-postfix:main
    container_name: postfix
    env_file:
      - .env
    ports:
      - '25:25'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./secrets/:/secrets/
    restart: unless-stopped
